- name: Install pip
  become: yes
  apt:
    name: ['python-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

# Update pip
- name: Update pip
  pip:
    name: ['pip']
    state: latest

# Install openstack
- name: Install openstacksdk
  pip:
    name: ["openstacksdk==0.52"]
    state: latest
